import type { Metadata } from 'next';
import { Roboto, Open_Sans } from 'next/font/google';
import Providers from '@/features/theme/ThemeProvider';

import './globals.scss';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['cyrillic'],
});

const open_sans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['cyrillic'],
});

export const metadata: Metadata = {
  title: 'My site',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru' suppressHydrationWarning>
      <body className={`${open_sans.variable} ${roboto.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
